name: Backend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'forge/**'
      - 'test/unit/**'
      - 'test/system/**'
      - 'package.json'
      - '.eslintrc'
  pull_request:
    paths:
      - 'forge/**'
      - 'test/unit/**'
      - 'test/system/**'
      - 'package.json'
      - '.eslintrc'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build the forge
      run: npm run build
    - name: Test the forge with code coverage
      run: npm run cover
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}